---
#-------------------------------
# Site Settings
title: Farouk Ben Fraj - Tech Lead & Software Developer
logo: /images/logo.png
author: Farouk Ben Fraj
description: A portfolio showcasing my expertise in React, NodeJS, and blockchain technologies, along with my journey in tech leadership and digital innovation.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    # - title: "Blog"
    #   url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"
    # - title: "Elements"
    #   url: "/elements/"

#-------------------------------
hero:
  hero__title: Hello, I’m Farouk Ben Fraj. A Tech Lead & Software Developer based in Paris.
  hero__description: Specializing in innovative digital solutions, my portfolio highlights my journey in tech, from full stack development to leading complex projects in React, NodeJS, and blockchain technologies.

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/gallery-01.jpg
      title: Samantha Gades
      description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

    - image: /images/gallery-02.jpg
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-04.jpg
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /images/gallery-05.jpg
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /images/gallery-06.jpg
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /images/gallery-07.jpg
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /images/gallery-08.jpg
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    - image: /images/gallery-09.jpg
      title: Books and Laptop
      description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>

#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).

#-------------------------------
# Footer Settings
social:
  - {
      icon: "ion-logo-linkedin",
      color: "#55acee",
      label: Linkedin,
      link: "https://www.linkedin.com/in/farouk-benfraj/",
    }
  - {
      icon: "ion-logo-github",
      color: "#24292e",
      label: Github,
      link: "https://github.com/fbenfraj",
    }

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: farouk.ben-fraj@frajtech.co
  description: Feel free to reach out to me for project inquiries, tech consultations, or just to say hi. Use the contact form or connect with me through my social channels.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
