---
#-------------------------------
# Site Settings
title: Farouk Ben Fraj - Tech Lead & Software Developer
logo: /images/logo.png
author: Farouk Ben Fraj
description: A portfolio showcasing my expertise in React, NodeJS, and blockchain technologies, along with my journey in tech leadership and digital innovation.

#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: "Home"
      url: "/"
    # - title: "Blog"
    #   url: "/blog/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"

#-------------------------------
hero:
  hero__title: Hello, I’m Farouk Ben Fraj. A Tech Lead & Software Developer based in Paris.
  hero__description: Specializing in innovative digital solutions, my portfolio highlights my journey in tech, from full stack development to leading complex projects in React, NodeJS, and blockchain technologies.

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/gateway-cover.jpg
      title: Odyssey (formerly Gateway)
      description: Brown photo frame beside wall <a href="https://www.mygateway.xyz/">mygateway.xyz</a>
      tags: ["React", "NodeJS", "Blockchain (Solidity)"]

    # - image: /images/gallery-02.jpg
    #   title: Raisponse
    #   description: Brown photo frame beside wall <a href="https://www.mygateway.xyz/">mygateway.xyz</a>
    # - image: /images/gallery-03.jpg
    #   title: Hotonome
    #   description: Brown photo frame beside wall <a href="https://www.mygateway.xyz/">mygateway.xyz</a>

#-------------------------------
# Portfolio Tags Settings
tag_icons:
  React: "logo-react"
  NodeJS: "logo-nodejs"
  "Blockchain (Solidity)": "logo-bitcoin"
  "Tech Leadership": "compass-outline"

#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).

#-------------------------------
# Footer Settings
social:
  - {
      icon: "logo-linkedin",
      color: "#55acee",
      label: Linkedin,
      link: "https://www.linkedin.com/in/farouk-benfraj/",
    }
  - {
      icon: "logo-github",
      color: "#24292e",
      label: Github,
      link: "https://github.com/fbenfraj",
    }

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Contact Settings
contact:
  email: farouk.ben-fraj@frajtech.co
  description: Feel free to reach out to me for project inquiries, tech consultations, or just to say hi. Use the contact form or connect with me through my social channels.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: G-ZPZCER5NRB
